# production-specific overrides
---
# enable our logs to be sent to a centralized server for processing later
# note: the magfest logging host currently only accepts whitelisted IPs
uber::log-filebeat::server_name_and_port:  'docker.magfest.net:9200'